###
### [http]
###
### Controls how the HTTP endpoints are configured.
###

[http]
  # The bind address used by the HTTP service.
  bind-address = ":18633"

###
### [dpm]
###
### Dataflow Performance Manager
###

[dpm]
  # DPM Enabled
  enabled = false

  # Base URL of the DPM
  base-url = "http://localhost:18631"

  # Application Token
  app-auth-token = ""
